# Generated by Django 4.2.3 on 2023-07-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapytrainingdata',
            old_name='topic',
            new_name='name',
        ),
    ]
