# Generated by Django 4.2.3 on 2023-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='sample_video',
            field=models.FileField(upload_to='sample_videos'),
        ),
    ]
