# Generated by Django 4.2.3 on 2023-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_avatar_sample_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='avatar_id',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='therapy_id',
            new_name='therapy',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_audio',
            field=models.FileField(upload_to='answer_audio/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='question_audio',
            field=models.FileField(upload_to='question_audio/'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
