# Generated by Django 4.2.3 on 2023-07-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_rename_avatar_id_conversation_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
