# Generated by Django 4.2.3 on 2023-07-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
