# Generated by Django 4.2.3 on 2023-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.FileField(upload_to='videos/')),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='theropy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('questions', models.TextField()),
                ('answers', models.TextField()),
            ],
        ),
    ]
