# Generated by Django 4.2.2 on 2023-07-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.FileField(upload_to='videos/')),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
